version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=${DOMAIN}
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - nginx-network
  api:
    image: ghcr.io/swd392-domus/domus-api:${API_VERSION}
    restart: unless-stopped
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
